name: run-tests

on:
    pull_request:
    push:
        branches-ignore:
            - main
            - next
        # Все пуши, попадающие в эти ветки, должны быть уже протестированы

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Начало
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  args: ${{ github.workflow }}
            - name: Начало
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_TO2 }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  args: ${{ github.workflow }}
            - uses: actions/setup-node@v2
            - name: Установка зависимостей
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  args: Установка зависимостей
            - name: Установка зависимостей
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_TO2 }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  args: Установка зависимостей
            - run: npm ci
            - name: Запуск тестов
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  args: Запуск тестов
            - name: Запуск тестов
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_TO2 }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  args: Запуск тестов
            - run: npx eslint src
