name: run-tests

on:
    pull_request:
    push:
        branches-ignore:
            - main
            - next
        # Все пуши, попадающие в эти ветки, должны быть уже протестированы

jobs:
    build:
        uses: appleboy/telegram-action@master
        with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
                ${{ github.repository }} начинает проходить тесты.
        args: The ${{ github.event_name }} event triggered first step.
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ["12", "14", "16"]
        name: Node ${{ matrix.node }} sample
        steps:
            - uses: actions/checkout@v2
            - name: Установка окружения.
              uses: appleboy/telegram-action@master
                with:
                    to: ${{ secrets.TELEGRAM_TO }}
                    token: ${{ secrets.TELEGRAM_TOKEN }}
                    message: |
                        ${{ github.event.name }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
            - name: Установка зависимостей.
              uses: appleboy/telegram-action@master
                  with:
                      to: ${{ secrets.TELEGRAM_TO }}
                      token: ${{ secrets.TELEGRAM_TOKEN }}
                      message: |
                          ${{ github.event.name }}
              run: npm ci
              name: Запуск линтера
              run: |
                  npx eslint src
              uses: appleboy/telegram-action@master
                  with:
                      to: ${{ secrets.TELEGRAM_TO }}
                      token: ${{ secrets.TELEGRAM_TOKEN }}
                      message: |
                          ${{ github.event.name }}
